### ISSUE TITLE
 rgba(255 is not a valid value for Int32

### ISSUE THREAD

**Issue by danvic712** [aspose-cells/Aspose.Cells-for-.NET#55]
I want to put an html string to a workbook cell (with some html element contains rgba in  css style) ,and then I use HtmlString, but this operate throw a error about  rgba(255 is not a valid value for Int32
The version I have using is Aspose.Cells 19.4.0
```csharp

//Datatable data

for (int i = 0; i < rows; i++)
{
    for (int k = 0; k < columns; k++)
    {
        cells[1 + i, k].HtmlString = data.Rows[i][k].ToString();
        cells[1 + i, k].SetStyle(style);
    }
}       
```

**Comment by amjad-sahi** [comment]
I think you should debug your code closely for the datatable field value(s) if it is ok, the issue may lie there. I have tested using the following code with static HTML string, it works fine and I do not find any issue. See the sample code that I am using:
e.g
**Sample code:**

```
Workbook wb = new Workbook();

            Worksheet ws = wb.Worksheets[0];

            Cell cell = ws.Cells["B5"];
            cell.HtmlString = "<p>This is what a bio <span style=\"color:rgb(255, 0, 0)\">teacher </span>does....lots of <span style=\"background-color:rgb(255, 215, 0)\">stuff</span>.</p> <ol> <li>You must be smart</li> <li><a href=\"http://www.google.com\">Patient</a></li> <li>Can type&nbsp;</li> <li>other stuffs.</li> </ol>";

            wb.Save("e:\\test2\\out1.xlsx");
```

If you still could not evaluate or find the issue, kindly do provide sample code (runnable) same as above, you may use static string or create dynamic Dataset/datatable in code to remove any inter-dependencies for external data sources to show the issue, so we could execute your code precisely to consequently figure it out soon.

**Comment by Lanesra712** [comment]
@amjad-sahi 
Hi, Here is my sample code, I tried html string which has rgb color model and that is fine , but when the html string has **rgba color**, and is still throw error
```csharp
static void Main(string[] args)
{
    Workbook wb = new Workbook();
    Worksheet ws = wb.Worksheets[0];

    Cell cell = ws.Cells["B5"];
    cell.HtmlString = "<span style='background-color: rgba(255, 255, 255, 0.8);'>lalalalalala</span>";

    wb.Save(@"C:\Users\danvic.wang\Desktop\demo.xlsx");
}
```
![20190507162522](https://user-images.githubusercontent.com/32116018/57284923-b733f200-70e4-11e9-8801-d602059e637b.png)

**Comment by amjad-sahi** [comment]
@Lanesra712 

Thanks for the code segment and screenshot with details.

After an initial test, I am able to observe the issue as you mentioned by using updated sample code. I found an exception "rgba(255 is not a valid value for Int32" when setting HTML string using rgba color model, it works fine if I use rgb instead:
e.g
**Sample code:**

```
Workbook wb = new Workbook();

 Worksheet ws = wb.Worksheets[0];

 Cell cell = ws.Cells["B5"];
//This works.            
//cell.HtmlString = "<p>This is what a bio <span style=\"color:rgb(255, 0, 0)\">teacher </span>does....lots of <span style=\"background-color:rgb(255, 215, 0)\">stuff</span>.</p> <ol> <li>You must be smart</li> <li><a href=\"http://www.google.com\">Patient</a></li> <li>Can type&nbsp;</li> <li>other stuffs.</li> </ol>";
//This does not work            
cell.HtmlString = "<span style='background-color: rgba(255, 255, 255, 0.8);'>lalalalalala</span>";

  wb.Save("e:\\test2\\out1.xlsx");
```
I have logged a ticket with an id "CELLSNET-46719" for your issue. We will look into it to figure it out soon. It is possible that we will share the fix which may fix your issue.

Once we have an update on it, we will let you know.

**Comment by ahsaniqbalsidiqui** [comment]
@Lanesra712 

This is to inform you that we have fixed your issue (logged earlier as “CELLSNET-46719”) now. We will soon provide you the fixed version after performing QA and incorporating other enhancements and fixes.

**Comment by Lanesra712** [comment]
@ahsaniqbalsidiqui 
Thanks~~~

**Comment by ahsaniqbalsidiqui** [comment]
@Lanesra712 
Please try our latest version/fix: Aspose.Cells for .NET v19.4.5 (attached)

Your issue should be fixed in it.

Let us know your feedback.
[Aspose.Cells19.4.5 For .Net2_AuthenticodeSigned.Zip](https://www.dropbox.com/s/yq53ktt779rbisd/Aspose.Cells19.4.5%20For%20.Net2_AuthenticodeSigned.Zip?dl=0)
[Aspose.Cells19.4.5 For .Net4.0.Zip](https://www.dropbox.com/s/gm46dp98z6if4e3/Aspose.Cells19.4.5%20For%20.Net4.0.Zip?dl=0)

**Comment by Lanesra712** [comment]
@ahsaniqbalsidiqui 
Hi,thanks for hard working, I download it and add it to my demo project, unfortunately it seems still have this bug, here is my demo, thanks.
Demo address：[aspose demo](https://1drv.ms/u/s!AvaRvJHWiQEtqvlhOH347uKDxWnuRA)

**Comment by amjad-sahi** [comment]
@Lanesra712 

Thanks for the demo project.

Please ignore our previous reply as the shared fix does not include your fix in it. We will share a hotfix in the next week (hopefully) which will figure out your issue.

Keep in touch.

**Comment by amjad-sahi** [comment]
@Lanesra712,

Please try our latest version/fix: Aspose.Cells for .NET v19.4.6 (attached)

Your issue should be fixed in it.

Let us know your feedback.
[Aspose.Cells19.4.6 For .Net2_AuthenticodeSigned.Zip](https://drive.google.com/file/d/1Z_wapJRGZxLEBhAXX6AcchT02JeHFtYD/view?usp=sharing)
[Aspose.Cells19.4.6 For .Net4.0.Zip](https://drive.google.com/file/d/1mnm5Acv67GslinoZwh46K2iySFy01g7U/view?usp=sharing)

**Comment by Lanesra712** [comment]
@amjad-sahi 
Thanks for hard working, this issue has been resolved , thanks

**Comment by amjad-sahi** [comment]
@Lanesra712,

Good to know that your issue is resolved with the new fix/version. Feel free to contact us any time if you have further queries or issue, we will be happy to assist you soon.

**Comment by BinodPanditJH** [comment]
How i can  do cell format.please help

**Comment by amjad-sahi** [comment]
@BinodPanditJH,

See the following sample code on how to format (apply background color, change font with color and do alignment, etc.) a cell in the worksheet for your reference:
e.g.
**Sample code:**
```cs
//Create a new workbook
Workbook workbook = new Workbook();
//Get the first(default) worksheet in the workbook
Worksheet SheetReport = workbook.Worksheets[0];

//Get the A1 cell
Cell cell = SheetReport.Cells["A1"];
//Insert a value
cell.PutValue("testin..");
// Create and specify style object
Style cellStyle = new CellsFactory().CreateStyle();
cellStyle.HorizontalAlignment = TextAlignmentType.Left;
cellStyle.VerticalAlignment = TextAlignmentType.Center;
cellStyle.Pattern = BackgroundType.Solid;
cellStyle.ForegroundColor = Color.Red;
// Sets Cell style font attributes
cellStyle.Font.Name = "Arial";
cellStyle.Font.IsBold = true;
cellStyle.Font.Size = 12;
cellStyle.Font.Color = Color.Yellow;

// Apply the style to the cell
cell.SetStyle(cellStyle);

//Save the Excel file
workbook.Save("e:\\test2\\out1.xlsx");
```

Moreover, please see the documents with examples on [Format Cells](https://docs.aspose.com/cells/net/cells-formatting/) for your complete reference.

Should you have further queries or issue, feel free to contact us in dedicated [forums](https://forum.aspose.com/c/cells/9).

**Comment by BinodPanditJH** [comment]
Thanks

**Comment by BinodPanditJH** [comment]
How to find range like  eg . Range[A5,A10]?

**Comment by amjad-sahi** [comment]
@BinodPanditJH ,

See the document on [managing ranges](https://docs.aspose.com/cells/net/managing-ranges/#create-range) for your reference.

We encourage you to try using our dedicated [forums](https://forum.aspose.com/c/cells/9) for your further queries or issue. We handle clients queries efficiently in the forums.

**Comment by BinodPanditJH** [comment]
How to remove green mark on cell 
![image](https://user-images.githubusercontent.com/112534407/190942359-ba122ecb-2322-4b03-993a-4aa737df5383.png)

**Comment by amjad-sahi** [comment]
@BinodPanditJH ,

> How to remove green mark on cell


Thanks for the template file and sample code.

If the numeric data is inserted as string, you will see green triangle saying “Number stored as text” on top left corner of the cell(s). Please note, to apply proper formatting or perform calculations upon the cells, you need to convert these string values (in the cells) to numeric values. Otherwise you will not be able to set your desired tasks.

You may use overloaded version of the method, e.g., Cell.PutValue(string stringvalue, bool isConverted) to convert each cells’ existing value (if possible) to numeric values, set the last argument to true. I think you may loop through all those cells in the column and use this overloaded version of the method to convert every possible string value to numeric value (if possible) for the same cell.
e.g.,
**Sample code:**
```cs
 ...............
      cell.PutValue(cell.StringValue, true);
......................
```
Hope, this helps a bit.

**Comment by BinodPanditJH** [comment]
Thanks amjad-sahi

**Comment by amjad-sahi** [comment]
@BinodPanditJH,

You are welcome.

**Comment by BinodPanditJH** [comment]
How to row and column hide?

**Comment by amjad-sahi** [comment]
@BinodPanditJH,

You can hide a row or column by using the [HideRow](https://reference.aspose.com/cells/net/aspose.cells/cells/methods/hiderow) and [HideColumn](https://reference.aspose.com/cells/net/aspose.cells/cells/methods/hidecolumn) methods of the [Cells](https://reference.aspose.com/cells/net/aspose.cells/cells) collection respectively. Both methods take the row and column index as a parameter to hide the specific row or column.

e.g.
**Sample code:**
```cs
// Instantiating a Workbook object
// Opening the Excel file through the file stream
Workbook workbook = new Workbook("Book1.xlsx");

// Accessing the first worksheet in the Excel file
Worksheet worksheet = workbook.Worksheets[0];

// Hiding the 3rd row of the worksheet
worksheet.Cells.HideRow(2);

// Hiding the 2nd column of the worksheet
worksheet.Cells.HideColumn(1);

// Saving the modified Excel file
workbook.Save("out1.xlsx");

```
Please note,  it is also possible to hide a row or column by setting the row height or column width to 0 respectively via relevant API.

Moreover, you can show/unhide any hidden row or column by using the [UnhideRow](https://reference.aspose.com/cells/net/aspose.cells/cells/methods/unhiderow) and [UnhideColumn](https://reference.aspose.com/cells/net/aspose.cells/cells/methods/unhidecolumn) methods of the [Cells](https://reference.aspose.com/cells/net/aspose.cells/cells) collection respectively.

Hope, this helps a bit.

We again ask you to use our dedicated [forums](https://forum.aspose.com/c/cells/9) for your queries or issue where we handle clients queries or issues efficiently.

**Comment by BinodPanditJH** [comment]
How to merge A and B column ? I want to used Colspan ,How to use???
Pls help

**Comment by amjad-sahi** [comment]
See the document on [merging cells](https://docs.aspose.com/cells/net/merging-and-unmerging-cells/) for your reference. Also, see the topic for further reference.
https://kb.aspose.com/cells/net/how-to-merge-cells-in-excel-using-csharp/

```
I want to used Colspan ,How to use???
```
Do you want to set HTML string to the cell, so it should be parsed and cells are merged automatically? If true,  you may use [Cell.HtmlString](https://reference.aspose.com/cells/net/aspose.cells/cell/htmlstring/) attribute to specify your desired HTML string to the cell. If not, kindly elaborate it on how you could implement merging cells in MS Excel manually, you may provide sample Excel file with your desired results. We will check and help you on how to do it via Aspose.Cells APIs.
